/* tslint:disable */
/* eslint-disable */
/**
 * ToDo REST API
 * ToDoアプリのREST API。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ToDoの登録情報
 * @export
 * @interface NewTodo
 */
export interface NewTodo {
    /**
     * ToDoの内容
     * @type {string}
     * @memberof NewTodo
     */
    text: string;
}

export function NewTodoFromJSON(json: any): NewTodo {
    return NewTodoFromJSONTyped(json, false);
}

export function NewTodoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewTodo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function NewTodoToJSON(value?: NewTodo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
    };
}

