/* tslint:disable */
/* eslint-disable */
/**
 * ToDo REST API
 * ToDoアプリのREST API。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ToDoのステータス
 * @export
 * @interface TodoStatus
 */
export interface TodoStatus {
    /**
     * ToDoのステータス
     * @type {boolean}
     * @memberof TodoStatus
     */
    completed: boolean;
}

export function TodoStatusFromJSON(json: any): TodoStatus {
    return TodoStatusFromJSONTyped(json, false);
}

export function TodoStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'completed': json['completed'],
    };
}

export function TodoStatusToJSON(value?: TodoStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'completed': value.completed,
    };
}

